### ISSUE TITLE
[1.4.1 - Minor Incompatibility (still)] lammOS, OpenBodyCam, and CozyImprovements' TerminalMonitorAlwaysOn

### ISSUE THREAD

**Issue by SeedyMcSeedface** [lammas321/lammOS-LethalCompany#8]
Sorry but it's me again.

Didn't get a chance to play with my group until last night and it seems that the option to keep the terminal monitor on from CozyImprovements is still causing the body cam view to not show up on the terminal and instead only show the exterior cam (i think if exteriorcam is either disabled or on a different monitor via GeneralImprovements it'll instead show just the radar map that's been enlarged - haven't tested this in particular yet but that's what was happening on my group's profile).

![1966720_20240212044426_1](https://github.com/lammas321/lammOS-LethalCompany/assets/155770932/3adf7f7a-49ac-4cf6-8929-20f817446014)

[LogOutput.log](https://github.com/lammas321/lammOS-LethalCompany/files/14236954/LogOutput.log)

If this is something that's possible to be rectified it would be nice, but it's a minor thing though.

Profile Code: 018d9cbd-25c9-9936-9338-cf6cd2059399

If there's anything else I can provide or do to help please let me know, thanks.

**Comment by lammas321** [comment]
This comes down to a slight order of execution problem and oversight on my part. Upon the terminal starting, CozyImprovements loads the startup terminal node onto the screen so that there's something there to see once you load into the game. The call to Terminal.LoadNewNode causes my mod to check for valid camera mods, and it finds one (in this case OpenBodyCams), and then saves the camera display from the bottom right monitor for usage later. Then StartOfRound.Start is called just a bit after, and OpenBodyCams replaces the camera on the bottom right monitor with their own, after my mod already saved the internal ship camera. Then, once you go to view the monitor on the terminal, it shows the saved camera, which isn't the expected camera. I've already made the fix and can release the update whenever

**Comment by SeedyMcSeedface** [comment]
Nice! Looking forward to it.

**Comment by lammas321** [comment]
This issue has been fixed in the new version 1.5.0!
